apiVersion: v1
kind: Service
metadata:
  name: taskflow-backend-service
  labels:
    app: taskflow-backend # Ensure this label matches the one in the ServiceMonitor
spec:
  ports:
    - port: 5000
      targetPort: 5000
      name: http
  selector:
    app: taskflow-backend # Make sure this matches the backend pod label


 