apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskflow-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:713923090919:certificate/a9ed4dcb-e6e3-4285-874a-22b0436afd2e"
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    external-dns.alpha.kubernetes.io/hostname: app.okorojeremiah.online
spec:
  ingressClassName: alb
  rules:
    - host: app.okorojeremiah.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskflow-frontend-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: taskflow-backend-service
                port:
                  number: 5000
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: taskflow-backend-service
                port:
                  number: 5000